spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Rates
    username: postgres
    password: Grond352
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
  flyway:
    enabled: True
    locations: classpath:db/migration
